ALTER TABLE IF EXISTS badges ALTER COLUMN IF EXISTS criteria_type SET DATA TYPE VARCHAR(40);
ALTER TABLE IF EXISTS badges ADD COLUMN IF NOT EXISTS category VARCHAR(20);
UPDATE badges SET category = 'CHALLENGE' WHERE category IS NULL;
ALTER TABLE IF EXISTS badges ALTER COLUMN IF EXISTS category SET NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN IF EXISTS role SET DATA TYPE VARCHAR(20);
ALTER TABLE IF EXISTS climb_logs ALTER COLUMN IF EXISTS status SET DATA TYPE VARCHAR(20);
ALTER TABLE IF EXISTS climb_logs ALTER COLUMN IF EXISTS result SET DATA TYPE VARCHAR(10);
ALTER TABLE IF EXISTS posts ALTER COLUMN IF EXISTS type SET DATA TYPE VARCHAR(20);
