ALTER TABLE IF EXISTS badges ALTER COLUMN IF EXISTS criteria_type SET DATA TYPE VARCHAR(40);
ALTER TABLE IF EXISTS badges ADD COLUMN IF NOT EXISTS category VARCHAR(20);
UPDATE badges SET category = 'CHALLENGE' WHERE category IS NULL;
ALTER TABLE IF EXISTS badges ALTER COLUMN IF EXISTS category SET NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN IF EXISTS role SET DATA TYPE VARCHAR(20);
ALTER TABLE IF EXISTS climb_logs ALTER COLUMN IF EXISTS status SET DATA TYPE VARCHAR(20);
ALTER TABLE IF EXISTS climb_logs ALTER COLUMN IF EXISTS result SET DATA TYPE VARCHAR(10);
ALTER TABLE IF EXISTS posts ALTER COLUMN IF EXISTS type SET DATA TYPE VARCHAR(20);
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS media_path TEXT;
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS media_kind VARCHAR(20);
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS media_count INT DEFAULT 0;
UPDATE posts
SET media_count = CASE
    WHEN media_path IS NULL OR TRIM(media_path) = '' OR TRIM(media_path) = '[]' THEN 0
    WHEN TRIM(media_path) LIKE '[%' THEN LENGTH(TRIM(media_path)) - LENGTH(REPLACE(TRIM(media_path), ',', '')) + 1
    ELSE 1
END
WHERE media_count IS NULL OR media_count = 0;
ALTER TABLE IF EXISTS posts ALTER COLUMN IF EXISTS media_count SET NOT NULL;
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS is_beta BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS route_name VARCHAR(100);
